version: "3.5"

services:
  db:
    build: postgres
    image: task_management_db:1.0.1
    restart: always
    environment:
      POSTGRES_DB: user-db
      POSTGRES_USER: dmitry
      POSTGRES_PASSWORD: dmitry

  db2:
    build: postgres2
    image: task_management_task_db:1.0.1
    restart: always
    environment:
      POSTGRES_DB: task-db
      POSTGRES_USER: dmitry
      POSTGRES_PASSWORD: dmitry

  pgAdmin:
    build: pgAdmin
    image: task_management_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "82:80"

  user-service:
    build: ./user-service
    image: task_management_user_service:1.0.2
    ports:
      - "9090:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  task-service:
    build: ./task-service
    image: task_management_task_service:1.0.1
    ports:
      - "9091:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db2

  swagger-ui:
    build: swagger-ui
    image: task_management_swagger_ui:1.1.3
    ports:
    - "81:8080"