version: "3.5"

services:
  db:
    build: postgres
    image: task_management_db:1.0.1
    restart: always
    environment:
      POSTGRES_DB: user-db
      POSTGRES_USER: dmitry
      POSTGRES_PASSWORD: dmitry
  pgAdmin:
    build: pgAdmin
    image: task_management_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "82:80"
  user-service:
    build: ./user-service
    image: task_management_user_service:1.0.2
    ports:
      - "9090:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
