spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_system
    username: postgres
    password: postgres

app:
  jwt:
    secret: mySecret
    issuer: MyIssuer
