spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://db2/task-db
    username: dmitry
    password: dmitry

app:
  jwt:
    secret: mySecret
    issuer: MyIssuer
